version: 0.2

phases:
   build:
      commands:
         - echo Entered the build phase .....
         - mvn clean package
   post_build:
      commands:
         - echo Build completed Successfully....
artifacts:
   files:
      - target/Spring-Aws-Pipeline.jar
   discard-paths: yes